version: '3'

services:

  app:
    container_name: x-proxy
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      WEB_PORT: ${WEB_PORT}
      TARGET_HOST: ${TARGET_HOST}
      TWITTER_HOST: ${TWITTER_HOST}
      X_HOST: ${X_HOST}
      API_HOST: ${API_HOST}
    volumes:
      - ./:/app

